---
title: "Rapport"
author: "Eric Guilmin et Maxime Chauveau"
date: "26/09/2019"
output: html_document
---

```{r setup, include=FALSE}
setwd("~/Maxime_Chauveau/Hackathon_vendee")
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
library(leaflet)
library(sf)
```



```{r load_data}

#Chargement des zones naturelles d'interets ecologique faunistique et floristique
df_znieff1 <- read_sf(dsn = './data/MESURE DE PROTECTION/SHAPE/ZNIEFF_I.shp')
df_znieff1 <- st_transform(df_znieff1, CRS("+proj=longlat +datum=WGS84"))

# Chargement stratégie de création des aires protégées
df_scap <- read_sf(dsn = './data/MESURE DE PROTECTION/SHAPE/SECTEURS_SCAP.shp')
df_scap <- st_transform(df_scap, CRS("+proj=longlat +datum=WGS84"))


sf_mesure_protect <- read_sf(dsn = './data/MESURE DE PROTECTION/SHAPE/RESERVE_NATURELLE_NATIONALE.shp')
sf_mesure_protect <- st_transform(sf_mesure_protect, CRS("+proj=longlat +datum=WGS84"))
```





```{r map}

# Coordonnee la Roche/Yon
lati = 46.6667
longi = -1.4333

leaflet() %>%
  addTiles() %>%
  addPolygons(data=df_znieff1) %>%
  addPolygons(data=df_scap) %>%
  setView(lat = lati, lng = longi, zoom = 7)
```

